name: 🚀 Run Unit Tests

on:
  [pull_request, push]

jobs:
  run:
    name: 🚀 Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🚀 Run
        shell: bash
        run: |
          pytest tree.py
